{% set name = "conpty" %}
{% set version = "1.23.20211.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/microsoft/terminal/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 9d120d95140f98537989143b124760fe83fdcf5bb7148c28a9894b2c88348eab
  - url: https://www.nuget.org/api/v2/package/Microsoft.Windows.ImplementationLibrary/1.0.240122.1
    fn: wil.zip
    sha256: 2762643e7865c42ac60d809fe951a813ae10960141e56bb74ad28843f2d6b5c1
    folder: packages/Microsoft.Windows.ImplementationLibrary.1.0.240122.1

build:
  number: 0
  script: 
    #- powershell -Command "(Get-Content '%SRC_DIR%\\src\\common.nugetversions.targets') -replace 'Terminal_EnsureNuGetPackageBuildImports', 'Terminal_EnsureNuGetPackageBuildImports_DISABLED' | Set-Content '%SRC_DIR%\\src\\common.nugetversions.targets'"
    #- msbuild src\winconpty\lib\winconptylib.vcxproj /p:SolutionDir=%SRC_DIR%\ /p:Configuration=Release /p:Platform=x64
    #- msbuild src\winconpty\lib\winconptylib.vcxproj /p:SolutionDir=%SRC_DIR%\ /p:RestorePackages=false /p:EnableSourceControlManagerQueries=false /p:EnableSourceLink=false /p:GitBranch=main /p:GitBaseVersionNumber={{ version }}

    - msbuild src\winconpty\dll\winconptydll.vcxproj /p:SolutionDir=%SRC_DIR%\ /p:Configuration=Release /p:Platform=x64
    - copy %SRC_DIR%\bin\x64\Release\conpty.dll %LIBRARY_BIN%\
    - copy %SRC_DIR%\bin\x64\Release\conpty.lib %LIBRARY_LIB%\
    - mkdir %LIBRARY_INC%\conpty
    - copy %SRC_DIR%\src\winconpty\inc\conpty.h %LIBRARY_INC%\conpty\
    - dumpbin /exports %SRC_DIR%\bin\x64\Release\conpty.dll
  skip: true  # [not win]

requirements:
  build:
    #- git
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/microsoft/terminal/tree/main/src/winconpty
  summary: Windows Pseudo Console (ConPTY)
  description: Windows Pseudo Console (ConPTY)
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/terminal/tree/main/src/winconpty
  doc_url: https://github.com/microsoft/terminal/tree/main/src/winconpty

extra:
  recipe-maintainers:
    - TS-ANC
