{% set name = "conpty" %}
{% set version = "1.23.20211.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/terminal/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9d120d95140f98537989143b124760fe83fdcf5bb7148c28a9894b2c88348eab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - {{ name.replace('-', '.') }}
  requires:
    - pip
  commands:
    - pip check

about:
  home: <PLEASE ADD HOME URL>
  summary: <PLEASE ADD SUMMARY>
  description: |
    <PLEASE ADD DESCRIPTION>
  license: <PLEASE ADD LICENSE>
  license_family: <PLEASE ADD LICENSE_FAMILY>
  license_file: <PLEASE_ADD_LICENSE_FILE>
  dev_url: <PLEASE ADD DEV URL>
  doc_url: <PLEASE ADD DOC URL>

extra:
  recipe-maintainers:
    - Jrice1317
